scsi: sd: remove unused sd_probe_types
Upstream Status: RHEL-only

Attend the following warning introduced by a downstream change:
drivers/scsi/sd.c:121:20: error: ‘sd_probe_types’ defined but not used [-Werror=unused-variable]
  121 | static const char *sd_probe_types[] = { "async", "sync" };
      |                    ^~~~~~~~~~~~~~

Fixes: bc573390ad32 ("scsi: sd: Add "probe_type" module parameter to allow synchronous probing")

Signed-off-by: Eric Chanudet <echanude@redhat.com>