automotive: enable HUGETLBFS to workaround build error
The automotive build fails due to:

00:07:40 In function ‘drm_pagemap_cpages’,
00:07:40     inlined from ‘drm_pagemap_migrate_to_devmem’ at drivers/gpu/drm/drm_pagemap.c:596:6:
00:07:40 ././include/linux/compiler_types.h:699:45: error: call to ‘__compiletime_assert_423’ declared with attribute error: BUILD_BUG failed
00:07:40   699 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
00:07:40       |                                             ^
00:07:40 ././include/linux/compiler_types.h:680:25: note: in definition of macro ‘__compiletime_assert’
00:07:40   680 |                         prefix ## suffix();                             \
00:07:40       |                         ^~~~~~
00:07:40 ././include/linux/compiler_types.h:699:9: note: in expansion of macro ‘_compiletime_assert’
00:07:40   699 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
00:07:40       |         ^~~~~~~~~~~~~~~~~~~
00:07:40 ./include/linux/build_bug.h:40:37: note: in expansion of macro ‘compiletime_assert’
00:07:40    40 | #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
00:07:40       |                                     ^~~~~~~~~~~~~~~~~~
00:07:40 ./include/linux/build_bug.h:60:21: note: in expansion of macro ‘BUILD_BUG_ON_MSG’
00:07:40    60 | #define BUILD_BUG() BUILD_BUG_ON_MSG(1, "BUILD_BUG failed")
00:07:40       |                     ^~~~~~~~~~~~~~~~
00:07:40 ./include/linux/huge_mm.h:113:28: note: in expansion of macro ‘BUILD_BUG’
00:07:40   113 | #define HPAGE_PMD_SHIFT ({ BUILD_BUG(); 0; })
00:07:40       |                            ^~~~~~~~~
00:07:40 ./include/linux/huge_mm.h:117:26: note: in expansion of macro ‘HPAGE_PMD_SHIFT’
00:07:40   117 | #define HPAGE_PMD_ORDER (HPAGE_PMD_SHIFT-PAGE_SHIFT)
00:07:40       |                          ^~~~~~~~~~~~~~~
00:07:40 drivers/gpu/drm/drm_pagemap.c:483:33: note: in expansion of macro ‘HPAGE_PMD_ORDER’
00:07:40   483 |                         order = HPAGE_PMD_ORDER;
00:07:40       |                                 ^~~~~~~~~~~~~~~

Because CONFIG_PGTABLE_HAS_HUGE_LEAVES is not set, HPAGE_PMD_SHIFT will
be set to BUILD_BUG and trigger the build failure.

CONFIG_PGTABLE_HAS_HUGE_LEAVES will be enabled when we enable HUGETLBFS
which automotive has disabled.

This is not the correct solution to this issue but to unblock our
pipelines let's enable this config for automotive.

Signed-off-by: Scott Weaver <scweaver@redhat.com>