redhat: rh_flags: mark !CONFIG_RHEL_DIFFERENCES stubs as static inline
The empty stubs of rh_print_flags() and rh_add_flag() in the
!CONFIG_RHEL_DIFFERENCES branch of include/linux/rh_flags.h have no
callers in that configuration -- the sole caller, in kernel/module/main.c,
is itself guarded by #ifdef CONFIG_RHEL_DIFFERENCES.

Under the kernel's default -Werror=unused-function this aborts the
build of every configuration where CONFIG_RHEL_DIFFERENCES is unset
(all Fedora configs, both native and cross), e.g.:

  ./include/linux/rh_flags.h:32:13: error: 'rh_add_flag' defined but
      not used [-Werror=unused-function]
  ./include/linux/rh_flags.h:31:13: error: 'rh_print_flags' defined
      but not used [-Werror=unused-function]

Mark both stubs 'static inline' -- the standard Linux-kernel idiom
for empty conditional stubs -- to silence the warning without
introducing a new caller.

Signed-off-by: Jonathan Steffan <jsteffan@fedoraproject.org>