rpmspec: do not BuildRequires bpftool on noarch
Turns out we also need to keep bpftool BuildRequires out of noarch as
well, at least on a recent centos koji build I bumped into it:

BuildError: error building package (arch noarch), mock exited with status (...)

Executing command: ['/usr/bin/dnf', 'builddep', '--installroot', (...)
(...)
DEBUG util.py:444:  No matching package to install: 'bpftool'
(...)
DEBUG util.py:444:  Not all dependencies satisfied
DEBUG util.py:444:  Error: Some packages could not be found.
DEBUG util.py:598:  Child return code was: 1
DEBUG util.py:169:  kill orphans

noarch doesn't build any kernel of course so just keep it out too.

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>