kernel.spec: move slabinfo and page_owner_sort debuginfo to tools-debuginfo
Backport of RHEL8 commit.

commit e3b2d7aef8ad82c55b6f526b1e1318aec3b94d8f
Author: Frantisek Hrbata <fhrbata@redhat.com>
Date:   Mon Apr 27 08:53:40 2020 -0400

    [redhat] redhat: move slabinfo and page_owner_sort debuginfo to tools-debuginfo

    Message-id: <20200427085340.GA5962@localhost.localdomain>
    Patchwork-id: 305261
    Patchwork-instance: patchwork
    O-Subject: [RHEL8.3] redhat: move slabinfo and page_owner_sort debuginfo to tools-debuginfo
    Bugzilla: 1828178
    RH-Acked-by: Rafael Aquini <aquini@redhat.com>
    RH-Acked-by: Vladis Dronov <vdronov@redhat.com>

    Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1828178
    Upstream Status: RHEL only
    Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28196548
    Tested: Verified that debuginfo files for slabinfo and page_owner_sort
            are included in tools-debuginfo instead of debuginfo-common

    Commit d06b1385849f3f5c1ff515888865ccb531ba90e9 ("redhat: spec: package and
    ship VM tools"), included in kernel-4.18.0-193.13.el8, added slabinfo and
    page_owner_sort tools. Unfortunatelly it missed to add the debuginfo for
    these tools to tools-debuginfo package. As a result of this there are two
    problems:

    1) The debug info, along with build-id links, is presented in debuginfo-common
       package, which is obviously wrong.

    2) Since debuginfo-common is installonlypkgs the osci installability test fails,
       because of conflicts on these files.
       Error: Transaction test error:
          file /usr/lib/debug/usr/bin/page_owner_sort.debug from install of
               kernel-debuginfo-common-x86_64-4.18.0-193.14.el8.x86_64 conflicts
               with file from package
               kernel-debuginfo-common-x86_64-4.18.0-193.13.el8.x86_64
          file /usr/lib/debug/usr/bin/slabinfo.debug from install of
               kernel-debuginfo-common-x86_64-4.18.0-193.14.el8.x86_64 conflicts
               with file from package
          kernel-debuginfo-common-x86_64-4.18.0-193.13.el8.x86_64

    Fixes: d06b1385849f ("redhat: spec: package and ship VM tools")
    Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Jiri Olsa <jolsa@redhat.com>